#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):

    result = []
    for i, ch in enumerate(s):
        # capitalize if lowercase letter AND
        # previous character is space
        if ch.islower() and (i == 0 or s[i-1] == ' '):
            result.append(ch.upper())
        else:
            result.append(ch)
    return ''.join(result)


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
